import {
  ProgramStructure,
  PublicTrustMetric,
  AccreditationCert,
  AdvisoryBoardMember,
  StudentProject,
  StudentProfile,
  IndustryAnnouncement,
  IndustryConcernTicket,
} from './types';

export const computerEngineeringProgram: ProgramStructure = {
  id: 'cpe-ai-2026',
  name: 'Bachelor of Engineering in Computer Engineering and Artificial Intelligence',
  degreeName: 'B.Eng. (Computer Engineering & AI)',
  faculty: 'Faculty of Engineering',
  department: 'Department of Computer Engineering',
  major: 'Computer Engineering and AI',
  totalCredits: 138,
  durationYears: 4,
  accreditedBy: ['ABET (Accreditation Board for Engineering and Technology)', 'AUN-QA (ASEAN University Network Quality Assurance)', 'Council of Engineers Thailand'],
  overview:
    'A future-focused engineering curriculum combining rigorous computer science fundamentals, scalable distributed systems, robotics, and applied artificial intelligence. Designed in collaboration with international industry advisory boards to ensure direct employability and strong research innovation.',
  creditBreakdown: [
    { category: 'Core & Fundamental Engineering', credits: 78, color: 'bg-blue-600' },
    { category: 'Major Electives & AI Specialization', credits: 24, color: 'bg-indigo-600' },
    { category: 'General Education & Transdisciplinary', credits: 24, color: 'bg-emerald-600' },
    { category: 'Industrial Internship & Capstone Project', credits: 12, color: 'bg-amber-600' },
  ],
  plos: [
    {
      code: 'PLO1',
      title: 'Engineering & Mathematical Foundations',
      category: 'Technical Competence',
      description: 'Apply comprehensive knowledge of mathematics, natural sciences, computing foundations, and engineering principles to formulate complex computer engineering models.',
      performanceIndicators: [
        'Demonstrates mastery of discrete structures, calculus, and linear algebra in computing.',
        'Applies hardware architecture principles to optimize software performance.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (1): Identify, formulate, and solve complex engineering problems.',
    },
    {
      code: 'PLO2',
      title: 'Problem Analysis & AI System Design',
      category: 'Problem Solving & Engineering Design',
      description: 'Design, implement, and evaluate intelligent computing systems, architectures, or algorithms to meet specified industrial needs while respecting constraints such as latency, security, and scalability.',
      performanceIndicators: [
        'Designs end-to-end data and machine learning pipelines.',
        'Balances trade-offs in cloud latency, concurrency, and compute costs.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (2): Apply engineering design to produce solutions that meet specified needs.',
    },
    {
      code: 'PLO3',
      title: 'Modern Tool Usage & Cloud Technologies',
      category: 'Technical Competence',
      description: 'Select and apply state-of-the-art engineering tools, cloud native architectures, containerized environments, and AI frameworks to modern engineering practices.',
      performanceIndicators: [
        'Proficient with Git, Docker, Kubernetes, and CI/CD pipelines.',
        'Leverages PyTorch, TensorFlow, and distributed inference engines.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (6): Develop and conduct appropriate experimentation and analyze data.',
    },
    {
      code: 'PLO4',
      title: 'Ethical, Sustainable, & Professional Conduct',
      category: 'Ethics & Professionalism',
      description: 'Recognize ethical and professional responsibilities in engineering situations, including AI bias, data privacy, environmental impact, and legal compliance.',
      performanceIndicators: [
        'Conducts algorithmic fairness assessments and privacy audits.',
        'Complies with GDPR, PDPA, and ISO/IEC 27001 standards.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (4): Recognize ethical and professional responsibilities.',
    },
    {
      code: 'PLO5',
      title: 'Multidisciplinary Collaboration & Communication',
      category: 'Communication & Leadership',
      description: 'Communicate effectively with a range of technical and non-technical audiences, functioning collaboratively on multidisciplinary and cross-functional teams.',
      performanceIndicators: [
        'Prepares clear system architecture documentation and API contracts.',
        'Leads sprint planning and cross-functional design reviews.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (3) & (5): Effective communication and collaborative teamwork.',
    },
    {
      code: 'PLO6',
      title: 'Lifelong Learning & Autonomous Innovation',
      category: 'Lifelong Learning & Innovation',
      description: 'Acquire and apply new technical knowledge as needed, using appropriate self-directed learning strategies to adapt to evolving industry requirements.',
      performanceIndicators: [
        'Conducts independent literature reviews and technical evaluations of emerging tools.',
        'Contributes to open-source software and technology research.',
      ],
      abetCriteriaMapping: 'ABET Criterion 3 (7): Acquire and apply new knowledge using appropriate learning strategies.',
    },
  ],
  courses: [
    {
      code: 'CPE101',
      title: 'Programming Methodology & Algorithmic Thinking',
      credits: 3,
      creditFormat: '3 (2-2-5)',
      lectureHours: 2,
      labHours: 2,
      selfStudyHours: 5,
      category: 'Core Engineering',
      year: 1,
      semester: 1,
      prerequisites: [],
      description: 'Foundations of structured programming, pointers, memory allocation, time complexity, and basic data structures using modern C++ and Python.',
      clos: [
        { id: 'c1-1', code: 'CLO1', description: 'Formulate algorithmic solutions for computational problems.', bloomLevel: 'Apply', mappedPloCode: 'PLO1' },
        { id: 'c1-2', code: 'CLO2', description: 'Implement bug-free, modular code adhering to industry standards.', bloomLevel: 'Apply', mappedPloCode: 'PLO3' },
      ],
      mappedPlos: [
        { ploCode: 'PLO1', level: 'Introductory' },
        { ploCode: 'PLO3', level: 'Introductory' },
      ],
    },
    {
      code: 'CPE201',
      title: 'Data Structures and Algorithms',
      credits: 4,
      creditFormat: '4 (3-2-7)',
      lectureHours: 3,
      labHours: 2,
      selfStudyHours: 7,
      category: 'Core Engineering',
      year: 2,
      semester: 1,
      prerequisites: ['CPE101'],
      description: 'Advanced data structures including AVL trees, graphs, heaps, dynamic programming, divide-and-conquer, and amortized complexity analysis.',
      clos: [
        { id: 'c2-1', code: 'CLO1', description: 'Analyze asymptotic time and space bounds of complex algorithms.', bloomLevel: 'Analyze', mappedPloCode: 'PLO1' },
        { id: 'c2-2', code: 'CLO2', description: 'Design optimal graph and tree structures for real-world scenarios.', bloomLevel: 'Create', mappedPloCode: 'PLO2' },
      ],
      mappedPlos: [
        { ploCode: 'PLO1', level: 'Reinforcing' },
        { ploCode: 'PLO2', level: 'Reinforcing' },
      ],
    },
    {
      code: 'CPE221',
      title: 'Database Systems & Data Warehousing',
      credits: 3,
      creditFormat: '3 (2-2-5)',
      lectureHours: 2,
      labHours: 2,
      selfStudyHours: 5,
      category: 'Core Engineering',
      year: 2,
      semester: 2,
      prerequisites: ['CPE201'],
      description: 'Relational algebra, SQL optimization, ACID transactions, NoSQL engines (MongoDB, Redis), and vector embeddings for AI pipelines.',
      clos: [
        { id: 'c3-1', code: 'CLO1', description: 'Design normalized relational schemas and document stores.', bloomLevel: 'Create', mappedPloCode: 'PLO2' },
        { id: 'c3-2', code: 'CLO2', description: 'Construct scalable query caching and index strategies.', bloomLevel: 'Apply', mappedPloCode: 'PLO3' },
      ],
      mappedPlos: [
        { ploCode: 'PLO2', level: 'Reinforcing' },
        { ploCode: 'PLO3', level: 'Reinforcing' },
      ],
    },
    {
      code: 'CPE312',
      title: 'Distributed Systems & Cloud Computing',
      credits: 3,
      creditFormat: '3 (2-2-5)',
      lectureHours: 2,
      labHours: 2,
      selfStudyHours: 5,
      category: 'Core Engineering',
      year: 3,
      semester: 1,
      prerequisites: ['CPE201'],
      description: 'Consensus protocols (Raft, Paxos), microservices architecture, Docker, Kubernetes, AWS/GCP cloud native patterns, and message streaming (Kafka).',
      clos: [
        { id: 'c4-1', code: 'CLO1', description: 'Deploy resilient microservices across cloud clusters with auto-scaling.', bloomLevel: 'Apply', mappedPloCode: 'PLO3' },
        { id: 'c4-2', code: 'CLO2', description: 'Assess network partitions, CAP theorem trade-offs, and fault tolerance.', bloomLevel: 'Evaluate', mappedPloCode: 'PLO2' },
      ],
      mappedPlos: [
        { ploCode: 'PLO2', level: 'Mastery' },
        { ploCode: 'PLO3', level: 'Mastery' },
      ],
    },
    {
      code: 'CPE331',
      title: 'Machine Learning & Deep Neural Networks',
      credits: 3,
      creditFormat: '3 (2-2-5)',
      lectureHours: 2,
      labHours: 2,
      selfStudyHours: 5,
      category: 'Major Elective',
      year: 3,
      semester: 1,
      prerequisites: ['CPE201'],
      description: 'Supervised and unsupervised learning, CNNs, Transformers, LLMs, fine-tuning, retrieval-augmented generation (RAG), and model quantization.',
      clos: [
        { id: 'c5-1', code: 'CLO1', description: 'Train and evaluate deep neural networks using PyTorch for computer vision and NLP.', bloomLevel: 'Apply', mappedPloCode: 'PLO2' },
        { id: 'c5-2', code: 'CLO2', description: 'Evaluate model fairness, explainability, and hallucination risks.', bloomLevel: 'Evaluate', mappedPloCode: 'PLO4' },
      ],
      mappedPlos: [
        { ploCode: 'PLO2', level: 'Mastery' },
        { ploCode: 'PLO3', level: 'Mastery' },
        { ploCode: 'PLO4', level: 'Reinforcing' },
      ],
    },
    {
      code: 'CPE345',
      title: 'Software Engineering & Agile Methodologies',
      credits: 3,
      creditFormat: '3 (2-2-5)',
      lectureHours: 2,
      labHours: 2,
      selfStudyHours: 5,
      category: 'Core Engineering',
      year: 3,
      semester: 2,
      prerequisites: ['CPE221'],
      description: 'Agile/Scrum ceremonies, domain-driven design, automated testing (unit, integration, e2e), code reviews, and enterprise architecture.',
      clos: [
        { id: 'c6-1', code: 'CLO1', description: 'Lead sprint backlogs and deliver iterative software increments.', bloomLevel: 'Apply', mappedPloCode: 'PLO5' },
        { id: 'c6-2', code: 'CLO2', description: 'Formulate security and privacy policies in software design.', bloomLevel: 'Create', mappedPloCode: 'PLO4' },
      ],
      mappedPlos: [
        { ploCode: 'PLO4', level: 'Mastery' },
        { ploCode: 'PLO5', level: 'Mastery' },
      ],
    },
    {
      code: 'CPE380',
      title: 'Co-operative Industrial Internship',
      credits: 6,
      creditFormat: '6 (0-40-0)',
      lectureHours: 0,
      labHours: 40,
      selfStudyHours: 0,
      category: 'Capstone & Co-op',
      year: 3,
      semester: 2,
      prerequisites: ['CPE345'],
      description: 'A full-time, 16-week immersion within a verified industry partner. Students work as junior software engineers, data scientists, or hardware analysts.',
      clos: [
        { id: 'c7-1', code: 'CLO1', description: 'Resolve enterprise-scale technical challenges in an active production environment.', bloomLevel: 'Create', mappedPloCode: 'PLO2' },
        { id: 'c7-2', code: 'CLO2', description: 'Operate with professional ethics, executive presentations, and cross-disciplinary agility.', bloomLevel: 'Evaluate', mappedPloCode: 'PLO5' },
      ],
      mappedPlos: [
        { ploCode: 'PLO2', level: 'Mastery' },
        { ploCode: 'PLO3', level: 'Mastery' },
        { ploCode: 'PLO4', level: 'Mastery' },
        { ploCode: 'PLO5', level: 'Mastery' },
        { ploCode: 'PLO6', level: 'Mastery' },
      ],
    },
    {
      code: 'CPE401',
      title: 'Capstone Senior Design Project I',
      credits: 3,
      creditFormat: '3 (1-4-4)',
      lectureHours: 1,
      labHours: 4,
      selfStudyHours: 4,
      category: 'Capstone & Co-op',
      year: 4,
      semester: 1,
      prerequisites: ['CPE380'],
      description: 'Industry-sponsored or research-driven project inception. Requirements engineering, architecture specification, prototyping, and feasibility defense.',
      clos: [
        { id: 'c8-1', code: 'CLO1', description: 'Formulate a comprehensive technical project proposal addressing real-world industry needs.', bloomLevel: 'Create', mappedPloCode: 'PLO2' },
        { id: 'c8-2', code: 'CLO2', description: 'Deliver high-impact technical demonstrations to external industry examiners.', bloomLevel: 'Apply', mappedPloCode: 'PLO5' },
      ],
      mappedPlos: [
        { ploCode: 'PLO2', level: 'Mastery' },
        { ploCode: 'PLO5', level: 'Mastery' },
        { ploCode: 'PLO6', level: 'Mastery' },
      ],
    },
    {
      code: 'CPE402',
      title: 'Capstone Senior Design Project II',
      credits: 3,
      creditFormat: '3 (0-6-3)',
      lectureHours: 0,
      labHours: 6,
      selfStudyHours: 3,
      category: 'Capstone & Co-op',
      year: 4,
      semester: 2,
      prerequisites: ['CPE401'],
      description: 'Full system implementation, automated testing, stress/benchmarking tests, open showcase exhibition, and final defense with industry jury.',
      clos: [
        { id: 'c9-1', code: 'CLO1', description: 'Deploy a production-grade software or hardware system with documented benchmarks.', bloomLevel: 'Create', mappedPloCode: 'PLO2' },
        { id: 'c9-2', code: 'CLO2', description: 'Analyze societal, environmental, and ethical impacts of the deployed solution.', bloomLevel: 'Evaluate', mappedPloCode: 'PLO4' },
      ],
      mappedPlos: [
        { ploCode: 'PLO1', level: 'Mastery' },
        { ploCode: 'PLO2', level: 'Mastery' },
        { ploCode: 'PLO3', level: 'Mastery' },
        { ploCode: 'PLO4', level: 'Mastery' },
        { ploCode: 'PLO5', level: 'Mastery' },
        { ploCode: 'PLO6', level: 'Mastery' },
      ],
    },
  ],
};

export const informationTechnologyProgram: ProgramStructure = {
  id: 'it-ds-2026',
  name: 'Bachelor of Science in Information Technology',
  degreeName: 'B.Sc. (IT)',
  faculty: 'Faculty of Science',
  department: 'Department of Information Technology',
  major: 'Data Science',
  totalCredits: 120,
  durationYears: 4,
  accreditedBy: ['AUN-QA (ASEAN University Network Quality Assurance)'],
  overview: 'Focuses on enterprise data infrastructure, business intelligence, and cloud administration.',
  creditBreakdown: [
    { category: 'Core IT', credits: 60, color: 'bg-indigo-600' },
    { category: 'Major Electives', credits: 30, color: 'bg-purple-600' },
    { category: 'General Education', credits: 24, color: 'bg-emerald-600' },
    { category: 'Internship', credits: 6, color: 'bg-amber-600' },
  ],
  plos: [],
  courses: []
};

export const programs: ProgramStructure[] = [computerEngineeringProgram, informationTechnologyProgram];

export const publicTrustMetrics: PublicTrustMetric[] = [
  {
    title: 'Graduate Employability Rate',
    value: '97.4%',
    change: '+2.1% YoY',
    badge: 'Verified Outcome',
    description: 'Graduates securing professional technical employment or continuing to graduate school within 6 months of graduation.',
    iconName: 'Award',
  },
  {
    title: 'Employer Satisfaction Score',
    value: '4.88 / 5.0',
    change: 'Top Tier Nationwide',
    badge: 'Annual Corporate Survey',
    description: 'Evaluated across 140+ corporate partners on technical competency, communication, and work ethic.',
    iconName: 'ThumbsUp',
  },
  {
    title: 'ABET & AUN-QA Accreditation',
    value: '100% Compliant',
    change: 'Certified to 2030',
    badge: 'International Standards',
    description: 'Full international accreditation under Washington Accord mutual recognition criteria.',
    iconName: 'ShieldCheck',
  },
  {
    title: 'Average Starting Compensation',
    value: '$58,500 / yr',
    change: '฿68,000 / mo local avg',
    badge: 'Industry Benchmark',
    description: 'Median first-year compensation package reported by alumni in Software, AI, and Cloud Infrastructure.',
    iconName: 'TrendingUp',
  },
];

export const accreditationCerts: AccreditationCert[] = [
  {
    body: 'ABET EAC',
    fullName: 'Engineering Accreditation Commission of ABET',
    level: 'Full International Accreditation (Washington Accord)',
    validUntil: 'September 2030',
    status: 'Accredited',
    verificationUrl: 'https://www.abet.org',
    description: 'Guarantees that the curriculum, lab infrastructure, faculty credentials, and student outcomes meet global engineering standards.',
  },
  {
    body: 'AUN-QA',
    fullName: 'ASEAN University Network Quality Assurance',
    level: 'Tier 1 Program Level Certification',
    validUntil: 'December 2028',
    status: 'Certified',
    verificationUrl: 'https://www.aunsec.org',
    description: 'Assesses expected learning outcomes, program specification, teaching & learning strategy, and stakeholder feedback loops.',
  },
  {
    body: 'ISO 21001:2018',
    fullName: 'Educational Organizations Management Systems',
    level: 'Institutional Quality Certification',
    validUntil: 'August 2027',
    status: 'Excellence',
    verificationUrl: 'https://www.iso.org',
    description: 'Verifies continuous improvement mechanisms, public transparency, and student satisfaction processes.',
  },
];

export const advisoryBoardMembers: AdvisoryBoardMember[] = [
  {
    name: 'Dr. Thanawat Malai',
    title: 'Vice President of Engineering',
    company: 'Agoda International',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    industrySector: 'Global Travel Tech & Distributed Systems',
    focusArea: 'High-Concurrency Backends & Real-time Analytics',
  },
  {
    name: 'Somchai Prasertkit',
    title: 'Head of Applied AI & Research',
    company: 'Kasikorn Business-Technology Group (KBTG)',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    industrySector: 'FinTech & Banking AI',
    focusArea: 'Large Language Models & Fraud Detection Pipelines',
  },
  {
    name: 'Elena Rostova',
    title: 'Director of Cloud Architecture',
    company: 'Google Cloud APAC',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    industrySector: 'Cloud Computing & Enterprise Infrastructure',
    focusArea: 'Kubernetes Orchestration & Sustainable Green Data Centers',
  },
  {
    name: 'Krit Vichitkarn',
    title: 'Chief Technology Officer',
    company: 'SCG Digital & Automation',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    industrySector: 'Industrial IoT & Smart Manufacturing',
    focusArea: 'Robotics Edge AI & Predictive Maintenance',
  },
];

export const studentProjects: StudentProject[] = [
  // 2026 Projects
  {
    id: 'prj-2026-01',
    title: 'Autonomous Vision-Guided Agricultural Drone Fleet for Precision Crop Spraying',
    academicYear: 2026,
    semester: 2,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'IoT & Robotics',
    teamMembers: [
      { name: 'Nattapong Siriporn', role: 'Computer Vision & Edge Model Optimization' },
      { name: 'Kamonrat Decha', role: 'Drone Swarm Mesh Network & ROS 2' },
      { name: 'Pongsakorn Tan', role: 'Cloud Dashboard & Spatial Analytics' },
    ],
    advisor: 'Assoc. Prof. Dr. Chusak Techavuth',
    industryPartner: 'Kubota AgriTech Innovation Lab',
    abstract:
      'A synchronized multi-drone fleet equipped with multispectral edge cameras running TensorRT-optimized YOLOv10 models to detect crop disease patches and apply micro-doses of organic pesticide in real-time, reducing chemical usage by 68%.',
    problemStatement:
      'Traditional blanket spraying consumes excessive pesticide, contaminates soil, and fails to combat micro-infections before they spread across acreage.',
    solutionHighlights: [
      'Edge inference latency under 22ms on Jetson Orin Nano modules.',
      'Decentralized peer-to-peer collision avoidance protocol.',
      'Telemetry streaming over private 5G and LoRaWAN.',
    ],
    techStack: ['Python', 'C++', 'PyTorch', 'ROS 2', 'TensorRT', 'FastAPI', 'React', 'Docker'],
    githubUrl: 'https://github.com/example-uni/agri-drone-swarm',
    demoVideoUrl: 'https://www.youtube.com/watch?v=sample-agri',
    featured: true,
    status: 'In Progress',
  },
  {
    id: 'prj-2026-02',
    title: 'TrustMed: Zero-Knowledge Health Record Exchange for Cross-Hospital Referrals',
    academicYear: 2026,
    semester: 1,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'Cybersecurity & Cloud',
    teamMembers: [
      { name: 'Wipada Suksombat', role: 'ZK-SNARKs Cryptographic Circuit Engineer' },
      { name: 'Arthit Wongsuwan', role: 'HL7 / FHIR Gateway & Microservices' },
    ],
    advisor: 'Asst. Prof. Dr. Sirikanya Pattana',
    industryPartner: 'Bangkok Hospital Medical Group',
    abstract:
      'A privacy-preserving patient referral platform utilizing zero-knowledge proofs to allow specialist doctors to verify patient medical conditions, lab histories, and allergies without decrypting sensitive private identifiable data.',
    problemStatement:
      'Medical data sharing between private hospital networks is hampered by liability risks, PDPA / HIPAA constraints, and vulnerable centralized databases.',
    solutionHighlights: [
      'ZK-SNARK proof verification time under 150ms on standard client browsers.',
      'Full FHIR standard compliance for existing electronic health record (EHR) systems.',
    ],
    techStack: ['Rust', 'Circom', 'Solidity', 'Go', 'Next.js', 'PostgreSQL', 'Docker'],
    githubUrl: 'https://github.com/example-uni/trustmed-zk',
    featured: true,
    status: 'In Progress',
  },
  {
    id: 'prj-2026-03',
    title: 'FinLLM: High-Throughput Financial News Sentiment & Volatility Forecasting Engine',
    academicYear: 2026,
    semester: 1,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'FinTech & Blockchain',
    teamMembers: [
      { name: 'Tee Chotiprasert', role: 'LLM Fine-Tuning & Quantization' },
      { name: 'Ploy Supaporn', role: 'Real-time WebSocket & Order Book Simulator' },
    ],
    advisor: 'Dr. Warut Charoensuk',
    industryPartner: 'InnovestX Securities',
    abstract:
      'Specialized 7B parameter financial language model quantized to 4-bit weights capable of processing 1,200 incoming financial news articles and regulatory filings per second to predict 15-minute price volatility bands.',
    problemStatement:
      'Generalist models hallucinate on nuanced financial jargon and suffer unacceptable latency for algorithmic market making and risk mitigation.',
    solutionHighlights: [
      'Domain-adapted LoRA fine-tuning on 10 years of SEC and SET filings.',
      'Sub-50ms token inference latency with vLLM engine.',
    ],
    techStack: ['Python', 'vLLM', 'Hugging Face', 'FastAPI', 'Apache Kafka', 'ClickHouse', 'TailwindCSS'],
    githubUrl: 'https://github.com/example-uni/finllm-engine',
    featured: false,
    status: 'In Progress',
  },

  // 2025 Projects
  {
    id: 'prj-2025-01',
    title: 'MicroDefect: Sub-Micron Wafer Surface Inspection using Hybrid Vision Transformers',
    academicYear: 2025,
    semester: 2,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'AI & Machine Learning',
    teamMembers: [
      { name: 'Tanawat Boonma', role: 'Vision Transformer Model Architect' },
      { name: 'Siriporn Kittiwat', role: 'Industrial Camera Integration & Hardware Rig' },
      { name: 'Peerawit Srisai', role: 'Full-stack Inspection Portal' },
    ],
    advisor: 'Assoc. Prof. Dr. Kittisak Chaiwong',
    industryPartner: 'Western Digital Thailand',
    abstract:
      'An industrial automated optical inspection (AOI) system deploying a lightweight hybrid Vision Transformer (ViT) to inspect semiconductor hard drive heads and silicon wafers at 99.8% recall rate with 0.12% false-alarm rate.',
    problemStatement:
      'Human visual inspection in cleanrooms causes fatigue-induced quality escape, while traditional CNNs struggle with variable lighting and minute scratching defects.',
    solutionHighlights: [
      'Deployed on assembly lines inspecting 140 parts per minute.',
      'Reduced annual scrap wafer loss by an estimated $210,000 for industry partner.',
    ],
    techStack: ['Python', 'PyTorch', 'ONNX', 'OpenCV', 'FastAPI', 'React', 'Electron'],
    githubUrl: 'https://github.com/example-uni/wafer-microdefect-vit',
    demoVideoUrl: 'https://www.youtube.com/watch?v=sample-wafer',
    featured: true,
    status: 'Completed',
  },
  {
    id: 'prj-2025-02',
    title: 'UrbanWatt: AI-Driven Community Microgrid Peer-to-Peer Solar Energy Trading',
    academicYear: 2025,
    semester: 2,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'CleanTech & Smart Cities',
    teamMembers: [
      { name: 'Anan Thongdee', role: 'Smart Contract & Distributed Consensus' },
      { name: 'Nichaphat Ratanakul', role: 'Solar Irradiance Forecasting (LSTM)' },
    ],
    advisor: 'Dr. Sompop Prasit',
    industryPartner: 'Provincial Electricity Authority (PEA)',
    abstract:
      'A blockchain-enabled smart meter and trading portal allowing residential prosumers with rooftop solar photovoltaic cells to trade excess electricity peer-to-peer with automated dynamic price discovery.',
    problemStatement:
      'Centralized utilities reject localized rooftop solar feed-in due to grid balancing constraints, preventing households from monetizing clean energy generation.',
    solutionHighlights: [
      'Custom hardware smart meter module running FreeRTOS with cryptographic chip.',
      '94% accurate 24-hour solar generation forecasting.',
    ],
    techStack: ['C++', 'FreeRTOS', 'Solidity', 'Python', 'TensorFlow', 'Vue.js', 'PostgreSQL'],
    githubUrl: 'https://github.com/example-uni/urbanwatt-microgrid',
    featured: false,
    status: 'Completed',
  },
  {
    id: 'prj-2025-03',
    title: 'DyslexiLearn: Multimodal Adaptive Reading Assistant for Dyslexic Elementary Students',
    academicYear: 2025,
    semester: 1,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'HealthTech',
    teamMembers: [
      { name: 'Chayanit Metha', role: 'Eye-Tracking & Gaze Estimator' },
      { name: 'Rattapoom Chaiprasit', role: 'Phonetic Speech Synthesizer & Frontend' },
    ],
    advisor: 'Asst. Prof. Dr. Sirikanya Pattana',
    industryPartner: 'National Institute for Child & Family Development',
    abstract:
      'An interactive tablet application using front-facing camera gaze tracking to pinpoint where dyslexic readers struggle, dynamically re-rendering typography, phoneme breaks, and audio hints.',
    problemStatement:
      'Children with dyslexia struggle in traditional classroom settings and frequently disengage due to cognitive exhaustion and embarrassment.',
    solutionHighlights: [
      'Tested with 180 elementary students across 4 public schools.',
      'Demonstrated a 34% increase in reading comprehension speed.',
    ],
    techStack: ['TypeScript', 'React Native', 'WebGaze.js', 'PyTorch Mobile', 'Node.js'],
    githubUrl: 'https://github.com/example-uni/dyslexilearn-app',
    demoVideoUrl: 'https://www.youtube.com/watch?v=sample-dyslexi',
    featured: false,
    status: 'Completed',
  },

  // 2024 Projects
  {
    id: 'prj-2024-01',
    title: 'FleetGuard: Automated Forklift Fleet Collision Avoidance using LiDAR SLAM',
    academicYear: 2024,
    semester: 2,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'IoT & Robotics',
    teamMembers: [
      { name: 'Krit Pongpanich', role: 'SLAM & 3D Point Cloud Mapping' },
      { name: 'Wiroj Thanakul', role: 'CAN Bus Controller & Braking Actuator' },
      { name: 'Kornkanok Jaiyen', role: 'Fleet Management Telemetry Dashboard' },
    ],
    advisor: 'Assoc. Prof. Dr. Chusak Techavuth',
    industryPartner: 'SCG Logistics & Supply Chain',
    abstract:
      'A retrofit 3D LiDAR safety kit for industrial forklifts capable of millimeter-precise pedestrian tracking in blind warehouse aisles with emergency speed limiting and automated stop controls.',
    problemStatement:
      'Industrial warehouse vehicle accidents cause hundreds of severe injuries annually and costly product damage in crowded logistics centers.',
    solutionHighlights: [
      'Successfully piloted across 12 forklifts at SCG Saraburi central hub.',
      'Zero collision incidents recorded throughout the 6-month trial.',
    ],
    techStack: ['C++', 'ROS 1/2', 'PCL (Point Cloud Library)', 'Python', 'Qt', 'CAN Bus'],
    githubUrl: 'https://github.com/example-uni/fleetguard-slam',
    featured: true,
    status: 'Completed',
  },
  {
    id: 'prj-2024-02',
    title: 'WildfireSentinel: Low-Cost Solar IoT Mesh for Early Forest Fire Detection',
    academicYear: 2024,
    semester: 1,
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    category: 'CleanTech & Smart Cities',
    teamMembers: [
      { name: 'Surachai Kongkaew', role: 'Embedded Low-Power Gas Sensor Node' },
      { name: 'Pimchanok Vong', role: 'LoRaWAN Long-Distance Mesh Routing' },
    ],
    advisor: 'Dr. Sompop Prasit',
    industryPartner: 'Royal Forest Department',
    abstract:
      'A ruggedized, solar-powered sensor node network deployed across mountainous terrain in Chiang Mai to detect volatile organic compounds (VOC) and thermal spikes 45 minutes before satellite thermal imaging.',
    problemStatement:
      'Seasonal forest fires cause severe PM2.5 atmospheric pollution; satellite passes occur hours too late to stop fire origin points.',
    solutionHighlights: [
      'Nodes operate autonomously for up to 3 years without battery replacement.',
      'Covers 15 km² radius using multihop LoRaWAN communication.',
    ],
    techStack: ['C (ESP-IDF)', 'LoRaWAN', 'Python', 'TimescaleDB', 'Grafana', 'Docker'],
    githubUrl: 'https://github.com/example-uni/wildfire-sentinel-mesh',
    featured: false,
    status: 'Completed',
  },
];

export const studentProfiles: StudentProfile[] = [
  // Internship Students
  {
    id: 'std-01',
    name: 'Kasidit Prasert',
    studentIdMasked: '6601****28',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    yearLevel: 'Year 3',
    gpa: 3.82,
    skills: ['Python', 'Go', 'Kubernetes', 'Docker', 'PostgreSQL', 'FastAPI', 'AWS'],
    category: 'internship',
    bio: 'High-performing Year 3 student specializing in backend architecture and cloud-native infrastructure. Completed distributed systems coursework and eager to join a fast-paced software engineering team.',
    email: 'kasidit.p@uni.ac.th',
    portfolioUrl: 'https://kasidit-dev.example.com',
    githubUrl: 'https://github.com/kasidit-p',
    linkedinUrl: 'https://linkedin.com/in/kasidit-p',
    internshipDetails: {
      availabilityWindow: 'Summer 2026 (June - August) & Co-op Fall 2026',
      preferredRoles: ['Backend Software Engineer', 'Cloud / DevOps Intern', 'Site Reliability Engineering'],
      targetIndustry: 'Tech Companies, FinTech, Distributed SaaS',
      status: 'Seeking Placement',
    },
  },
  {
    id: 'std-02',
    name: 'Nutcha Thanarath',
    studentIdMasked: '6601****54',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    yearLevel: 'Year 3',
    gpa: 3.91,
    skills: ['PyTorch', 'Computer Vision', 'OpenCV', 'Python', 'React', 'TailwindCSS', 'C++'],
    category: 'internship',
    bio: 'Aspiring AI engineer with hands-on experience training YOLOv10 object detection and multimodal vision models. Winner of the 2025 National AI Hackathon.',
    email: 'nutcha.t@uni.ac.th',
    portfolioUrl: 'https://nutcha-ai.example.com',
    githubUrl: 'https://github.com/nutcha-t',
    linkedinUrl: 'https://linkedin.com/in/nutcha-t',
    internshipDetails: {
      availabilityWindow: 'Summer 2026 (June - August)',
      preferredRoles: ['Machine Learning Engineer Intern', 'Computer Vision Intern', 'Full-Stack AI Developer'],
      targetIndustry: 'AI Labs, Autonomous Systems, HealthTech',
      status: 'Interviewing',
    },
  },

  // Research Students
  {
    id: 'std-03',
    name: 'Dr. Thitiwan Saengchan (Ph.D. Candidate)',
    studentIdMasked: '6409****02',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=150&auto=format&fit=crop&q=80',
    department: 'Department of Computer Engineering',
    major: 'Ph.D. in Computer Engineering',
    yearLevel: 'Ph.D. Candidate',
    gpa: 3.96,
    skills: ['Large Language Models', 'Retrieval-Augmented Generation', 'Reinforcement Learning from Human Feedback', 'PyTorch', 'Distributed Training (Slurm)'],
    category: 'research',
    bio: 'Doctoral researcher investigating hallucination mitigation and structured reasoning in domain-specific medical and legal LLMs.',
    email: 'thitiwan.s@uni.ac.th',
    portfolioUrl: 'https://thitiwan-research.example.com',
    githubUrl: 'https://github.com/thitiwan-research',
    linkedinUrl: 'https://linkedin.com/in/thitiwan-s',
    researchDetails: {
      labName: 'Language & Cognitive Intelligence Lab (LCIL)',
      advisor: 'Assoc. Prof. Dr. Chusak Techavuth',
      researchDomain: 'Natural Language Processing & Knowledge Graphs',
      publications: [
        {
          title: 'Graph-Constrained Decoding for Zero-Hallucination Medical Query Synthesis',
          venue: 'ACL 2025 (Long Paper)',
          year: 2025,
        },
        {
          title: 'Efficient 4-bit LoRA Fine-Tuning Benchmarks on Multilingual Low-Resource Corpora',
          venue: 'IEEE Transactions on Artificial Intelligence',
          year: 2024,
        },
      ],
    },
  },
  {
    id: 'std-04',
    name: 'Chatchai Meethai (M.Sc. Student)',
    studentIdMasked: '6508****19',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    department: 'Department of Computer Engineering',
    major: 'M.Sc. in Robotics & Intelligent Systems',
    yearLevel: 'M.Sc. Year 2',
    gpa: 3.88,
    skills: ['ROS 2', 'LiDAR SLAM', 'C++', 'Control Systems', 'Kalman Filtering', 'Gazebo'],
    category: 'research',
    bio: 'Graduate researcher focusing on cooperative multi-agent navigation in GPS-denied underground tunnels and industrial warehouses.',
    email: 'chatchai.m@uni.ac.th',
    portfolioUrl: 'https://chatchai-robotics.example.com',
    githubUrl: 'https://github.com/chatchai-m',
    researchDetails: {
      labName: 'Autonomous Robotics & Cyber-Physical Systems Lab',
      advisor: 'Dr. Sompop Prasit',
      researchDomain: 'Autonomous Mobile Robots (AMR) & Industrial SLAM',
      publications: [
        {
          title: 'Decentralized Keyframe Selection for Multi-UAV Collaborative 3D Mapping',
          venue: 'IEEE IROS 2025',
          year: 2025,
        },
      ],
    },
  },

  // Student Activity & Leadership
  {
    id: 'std-05',
    name: 'Pakorn Rattanasri',
    studentIdMasked: '6501****88',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    department: 'Department of Computer Engineering',
    major: 'Computer Engineering & AI',
    yearLevel: 'Year 4',
    gpa: 3.75,
    skills: ['Next.js', 'TypeScript', 'Event Leadership', 'Product Management', 'DevRel', 'UI/UX'],
    category: 'activity_leader',
    bio: 'President of the University Developer Club and Google Developer Student Club (GDSC) Lead. Led 12 campus tech bootcamps with 1,200+ student attendees.',
    email: 'pakorn.r@uni.ac.th',
    portfolioUrl: 'https://pakorn-portfolio.example.com',
    githubUrl: 'https://github.com/pakorn-r',
    linkedinUrl: 'https://linkedin.com/in/pakorn-r',
    activityDetails: {
      roles: [
        {
          title: 'Google Developer Student Club (GDSC) Lead',
          organization: 'Google Developers & University Chapter',
          year: 2025,
          achievement: 'Organized Southeast Asia Student Solution Challenge, coaching 18 student startup teams.',
        },
        {
          title: 'Head of Hackathon Organizing Committee',
          organization: 'Faculty Engineering Student Council',
          year: 2024,
          achievement: 'Secured $15,000 in industry sponsorship and managed 250 hackers over 48 hours.',
        },
      ],
    },
  },
];

export const initialAnnouncements: IndustryAnnouncement[] = [
  {
    id: 'ann-01',
    companyName: 'Agoda International',
    companyLogoText: 'AG',
    industrySector: 'Global Travel Technology',
    title: 'Associate Software Engineer - 2026 Graduate Program',
    type: 'Full-Time Staff',
    location: 'CentralWorld Office, Bangkok',
    workMode: 'Hybrid',
    stipendOrSalary: '฿65,000 - ฿85,000 / month + Signing Bonus',
    deadline: '2026-10-31',
    description:
      'Join one of the fastest-growing travel tech companies globally. You will build high-concurrency distributed booking engines handling tens of thousands of requests per second using Scala, Java, and React.',
    requirements: [
      'Graduating in Computer Engineering, Computer Science, or related fields in 2026.',
      'Strong grasp of data structures, algorithms, and object-oriented design.',
      'Familiarity with relational databases and RESTful/gRPC API architecture.',
      'Fluency in English communication.',
    ],
    contactEmail: 'grad-recruitment@agoda.com',
    website: 'https://careersatagoda.com',
    postedDate: '2026-09-02',
    active: true,
    applicationCount: 38,
  },
  {
    id: 'ann-02',
    companyName: 'Kasikorn Business-Technology Group (KBTG)',
    companyLogoText: 'KB',
    industrySector: 'Banking & Financial Technology',
    title: 'AI & Data Science Summer Intern (Cohort 2026)',
    type: 'Internship / Co-op',
    location: 'KBTG Building, Chaengwattana',
    workMode: 'Hybrid',
    stipendOrSalary: '฿18,000 / month + Free Transportation & Lunch Allowance',
    deadline: '2026-11-15',
    description:
      'A structured 10-week summer internship where students work directly with our AI research team on NLP Thai language models, biometric verification, and predictive credit analytics.',
    requirements: [
      'Year 3 or Year 4 students in Computer Engineering, AI, or Mathematics.',
      'Proficiency in Python, PyTorch, Pandas, and Scikit-Learn.',
      'Experience with transformer architectures or computer vision is a plus.',
    ],
    contactEmail: 'internship@kbtg.tech',
    website: 'https://kbtg.tech/careers',
    postedDate: '2026-09-05',
    active: true,
    applicationCount: 52,
  },
  {
    id: 'ann-03',
    companyName: 'Linx Robotics & Automation',
    companyLogoText: 'LX',
    industrySector: 'Industrial Automation & Robotics',
    title: 'Sponsored Capstone Grant: Autonomous Warehouse Pallet Jack Vision Guidance',
    type: 'Sponsored Capstone',
    location: 'Chonburi High-Tech Industrial Zone',
    workMode: 'On-site',
    stipendOrSalary: '฿120,000 Project Budget + Hardware Provided',
    deadline: '2026-10-15',
    description:
      'Linx Robotics is sponsoring 2 senior design project teams (Year 4) to develop stereo-vision pallet detection algorithms. Hardware (stereoscopic cameras, industrial compute boards) and engineer mentorship provided.',
    requirements: [
      'Capstone teams of 2-3 final-year Computer or Mechanical Engineering students.',
      'Passionate about ROS 2, OpenCV, and embedded Linux.',
      'Commitment to deliver milestone prototypes and final exhibition defense.',
    ],
    contactEmail: 'innovation@linxrobotics.com',
    website: 'https://linxrobotics.example.com',
    postedDate: '2026-08-28',
    active: true,
    applicationCount: 6,
  },
  {
    id: 'ann-04',
    companyName: 'CloudScale Asia',
    companyLogoText: 'CS',
    industrySector: 'Cloud Solutions & Managed DevOps',
    title: 'Cloud Security & DevSecOps Engineer',
    type: 'Full-Time Staff',
    location: 'Sathorn, Bangkok',
    workMode: 'Remote',
    stipendOrSalary: '฿55,000 - ฿75,000 / month',
    deadline: '2026-10-20',
    description:
      'Seeking fresh graduates or junior engineers with hands-on curiosity in Terraform, AWS/GCP security postures, and automated container image scanning.',
    requirements: [
      'Hands-on experience with Linux CLI, Bash, and Python.',
      'Foundational understanding of network protocols, TLS, VPCs, and IAM policies.',
      'Relevant cloud certifications (AWS SAA or CKA) are highly advantageous.',
    ],
    contactEmail: 'hr@cloudscaleasia.io',
    website: 'https://cloudscaleasia.io',
    postedDate: '2026-09-08',
    active: true,
    applicationCount: 19,
  },
];

export const initialConcernTickets: IndustryConcernTicket[] = [
  {
    id: 'tck-01',
    ticketNumber: 'TCK-2026-004',
    companyName: 'Agoda International',
    submitterName: 'Dr. Thanawat Malai',
    submitterRole: 'VP of Engineering',
    submitterEmail: 'thanawat.m@agoda.com',
    category: 'Curriculum Skill Gap',
    priority: 'High',
    subject: 'Integrate Event-Driven Architecture & Kafka Streaming into Year 3 Curriculum',
    description:
      'In our recent recruitment of university graduates, students exhibited exceptional algorithmic knowledge and relational database skills, but were inexperienced with distributed event streaming (e.g. Apache Kafka, RabbitMQ) and eventual consistency paradigms used across modern high-scale internet companies.',
    suggestedAction:
      'Add a dedicated 2-week lab module in CPE312 (Distributed Systems) where students build a streaming pub/sub system with Kafka and handle idempotent consumers.',
    status: 'Action Plan Drafted',
    createdAt: '2026-08-15',
    assignedCommittee: 'Curriculum & Continuous Quality Improvement Committee',
    committeeResponse:
      'Reviewed in August 2026 CQI session. The department chair approved integrating a hands-on Kafka streaming project into CPE312 starting Semester 1, Academic Year 2026. Lab materials currently under development.',
  },
  {
    id: 'tck-02',
    ticketNumber: 'TCK-2026-008',
    companyName: 'KBTG',
    submitterName: 'Somchai Prasertkit',
    submitterRole: 'Head of Applied AI',
    submitterEmail: 'somchai.p@kbtg.tech',
    category: 'Curriculum Skill Gap',
    priority: 'Medium',
    subject: 'Emphasis on AI Model Governance, PDPA Compliance & Prompt Safety',
    description:
      'Graduates entering financial AI roles must understand that model deployment involves strict regulatory compliance, PDPA data privacy, and mitigation of prompt injection. We recommend introducing AI governance frameworks into the AI elective course.',
    suggestedAction:
      'Incorporate OWASP Top 10 for LLMs and PDPA compliance auditing as part of CPE331 or CPE345 coursework.',
    status: 'Committee Review',
    createdAt: '2026-09-01',
    assignedCommittee: 'AI Track Advisory Sub-committee',
    committeeResponse:
      'The issue was placed on the agenda for the upcoming September 2026 Curriculum Council meeting. We plan to invite guest lecturers from KBTG to co-design the case studies.',
  },
  {
    id: 'tck-03',
    ticketNumber: 'TCK-2025-042',
    companyName: 'Western Digital Thailand',
    submitterName: 'Jiraporn Suthisan',
    submitterRole: 'Director of Advanced Manufacturing',
    submitterEmail: 'jiraporn.s@wdc.com',
    category: 'Internship Preparedness',
    priority: 'High',
    subject: 'Extension of Industrial Internship Duration from 8 Weeks to 16 Weeks (Co-op)',
    description:
      'An 8-week summer internship is too short for engineering interns to onboard, complete cleanroom safety clearance, and produce a substantive project. A full 16-week or 6-month cooperative education track is necessary for real industry impact.',
    suggestedAction:
      'Restructure the 6th and 7th semesters to permit a dedicated 6-month continuous Co-op option awarding 6-9 academic credits.',
    status: 'Resolved',
    createdAt: '2025-04-12',
    assignedCommittee: 'University Academic Senate',
    committeeResponse:
      'Implemented in the revised 2026 curriculum structure: Course CPE380 has been officially expanded into a full 16-week (6 credit) cooperative education track during Semester 2 of Year 3.',
  },
];
